//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cakedbEntities : DbContext
    {
        public cakedbEntities()
            : base("name=cakedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Address> T_Address { get; set; }
        public virtual DbSet<T_Content> T_Content { get; set; }
        public virtual DbSet<T_ContentCategory> T_ContentCategory { get; set; }
        public virtual DbSet<T_IntegralLog> T_IntegralLog { get; set; }
        public virtual DbSet<T_OrderDetail> T_OrderDetail { get; set; }
        public virtual DbSet<T_ProductCategory> T_ProductCategory { get; set; }
        public virtual DbSet<T_UserClass> T_UserClass { get; set; }
        public virtual DbSet<T_UserGrade> T_UserGrade { get; set; }
        public virtual DbSet<T_ProductDetail> T_ProductDetail { get; set; }
        public virtual DbSet<T_ProductComment> T_ProductComment { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<T_Cart> T_Cart { get; set; }
        public virtual DbSet<T_Order> T_Order { get; set; }
        public virtual DbSet<T_OrderLog> T_OrderLog { get; set; }
        public virtual DbSet<T_Admin> T_Admin { get; set; }
        public virtual DbSet<T_Protuct> T_Protuct { get; set; }
    }
}
