//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Admin
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Pwd { get; set; }
        public string Mobile { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string Competence { get; set; }
        public Nullable<System.DateTime> LoginDate { get; set; }
        public string LoginIP { get; set; }
        public string RealName { get; set; }
        public string Email { get; set; }
        public string admintoken { get; set; }
    }
}
