//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_IntegralLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> MaKaCurrency { get; set; }
        public string IntegralClass { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public Nullable<int> InvitationNumber { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ClientIP { get; set; }
        public string Remark { get; set; }
    }
}
