//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OrderLog
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public string PayCode { get; set; }
        public string PayType { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public string PayStatus { get; set; }
        public string Remark { get; set; }
    }
}
