//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order
    {
        public int Id { get; set; }
        public string OrderCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ProductName { get; set; }
        public string Adress { get; set; }
        public string Remark { get; set; }
        public string Mobile { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public string OrderStatus { get; set; }
        public string CreateIP { get; set; }
        public string PayType { get; set; }
        public string card_birthday { get; set; }
        public string bastdate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<decimal> fare { get; set; }
        public Nullable<int> makabi { get; set; }
        public string paycode { get; set; }
    }
}
