//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Protuct
    {
        public int Id { get; set; }
        public string ProductTitle { get; set; }
        public string Imgurl1 { get; set; }
        public string Imgurl2 { get; set; }
        public string ProductContent { get; set; }
        public string Remark { get; set; }
        public string productdec { get; set; }
        public Nullable<int> Category { get; set; }
        public string CategoryName { get; set; }
        public string Imgurl3 { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> SaleNumber { get; set; }
    }
}
