//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ProductDetail
    {
        public int Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Size { get; set; }
        public string Tableware { get; set; }
        public string Perpole { get; set; }
        public Nullable<int> Specification { get; set; }
        public string Remark { get; set; }
        public Nullable<int> ProductId { get; set; }
    }
}
