//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cake_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public int Id { get; set; }
        public string NiceName { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Pwd { get; set; }
        public Nullable<int> GradeId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ClassId { get; set; }
        public string WeiboCode { get; set; }
        public string WeixinCode { get; set; }
        public string InvitationCode { get; set; }
        public Nullable<int> InvitationNumber { get; set; }
        public Nullable<int> MaKaCurrency { get; set; }
        public Nullable<decimal> OrderPrice { get; set; }
        public string Token { get; set; }
        public Nullable<int> UserId { get; set; }
        public string GradeName { get; set; }
    }
}
